cygnet3/danawallet

lib/main.dart
lib/spend.dart

Some minor changes related to the sp_backend change branch

Output status

---

rust/justfile

Update of the gen command in justfile

Update justfile gen

---

lib/destination.dart
pubspec.lock
pubspec.yaml

Add bip353 support for sending to an email-like address.

Add bip353

---

lib/constants.dart
lib/generated/rust/api/wallet.dart
lib/generated/rust/frb_generated.dart
lib/global_functions.dart
lib/screens/create/create_wallet.dart
lib/screens/home/settings/settings.dart
lib/screens/home/wallet/wallet.dart
lib/services/settings_service.dart
lib/states/theme_notifier.dart
lib/states/wallet_state.dart
lib/widgets/input_alert_widget.dart
rust/src/api/wallet.rs
rust/src/blindbit/client.rs
rust/src/blindbit/logic.rs
rust/src/frb_generated.rs

Add dust limit, and make it adjustable in the settings page

---

lib/constants.dart
lib/screens/create/create_wallet.dart
lib/screens/home/wallet/wallet.dart
lib/states/chain_state.dart
rust/src/blindbit/client.rs

Proper error handling when failing to get block height

---

lib/generated/rust/api/psbt.dart
lib/generated/rust/frb_generated.dart
lib/screens/home/wallet/spend/spend.dart
rust/src/api/psbt.rs
rust/src/frb_generated.rs

Make sending function async (so it doesn't freeze the UI), add error display to the screen, and add a loading bar while sending.
Closes #35

Improve sending flow

---

lib/generated/rust/api/psbt.dart
lib/generated/rust/api/structs.dart
lib/generated/rust/api/wallet.dart
lib/generated/rust/frb_generated.dart
lib/generated/rust/frb_generated.io.dart
lib/generated/rust/frb_generated.web.dart
lib/screens/home/wallet/spend/spend.dart
lib/states/wallet_state.dart
rust/Cargo.lock
rust/Cargo.toml
rust/src/api/psbt.rs
rust/src/api/structs.rs
rust/src/api/wallet.rs
rust/src/frb_generated.rs

Add unconfirmed change outputs to total balance

---

lib/global_functions.dart
lib/screens/home/settings/settings.dart
lib/screens/home/wallet/spend/spend.dart
lib/screens/home/wallet/wallet.dart
lib/services/synchronization_service.dart

Format error messages to remove stack trace

---

lib/screens/home/wallet/spend/spend.dart
lib/states/spend_state.dart

Move all spending logic from screen to SpendState

Refactor spending logic

---

lib/generated/rust/api/wallet.dart
lib/generated/rust/frb_generated.dart
lib/screens/home/settings/settings.dart
lib/screens/home/wallet/wallet.dart
lib/states/scan_progress_notifier.dart
lib/states/wallet_state.dart
rust/Cargo.lock
rust/Cargo.toml
rust/src/api/wallet.rs
rust/src/frb_generated.rs
rust/src/wallet/mod.rs
rust/src/wallet/wallet.rs

Closes #44 
Also fixes bug where the scan function would update wallet data, despite the wallet already being deleted.
Also contains a slight redesign of the wallet overview page.

Add interrupt feature for scanning

---

rust/Cargo.lock
rust/src/api/wallet.rs
rust/src/wallet/updater.rs

Integrate some refactorings of sp-client.

Update sp-client to latest

---

lib/global_functions.dart
lib/screens/home/settings/settings.dart
lib/widgets/confirmation_widget.dart

Add a confirmation screen when attempting to wipe the wallet

---

lib/screens/home/wallet/spend/spend.dart
lib/states/spend_state.dart

#88 : Display the available balance above the amount text field
#87 : Add a 'Max' button at the right of the amount text field
#93 : In case we're not up to date, display a small message just below the available balance

Spend display available

---

lib/global_functions.dart
lib/screens/home/settings/settings.dart
lib/widgets/input_alert_widget.dart

Closes #84 
Also adds 'reset to default' option for other settings.

Reset to default option

---

lib/screens/home/wallet/spend/spend.dart
lib/widgets/qr_code_scanner_widget.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

Add Qr scanner to fill address field

---

lib/screens/create/create_wallet.dart

Add warning message when selecting mainnet on 'create wallet' page

---

lib/screens/create/create_wallet.dart

Remove testnet from create wallet network options

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
lib/constants.dart
lib/global_functions.dart
lib/main.dart
lib/main_dev.dart
lib/screens/home/settings/settings.dart
lib/states/wallet_state.dart

- Adds android support for a 'dev' flavor
- Adds a 'main_dev' file
- Hide buttons based on whether we're in 'dev' flavor or not
- Read extra command line arguments if we're in a 'dev' environment
Closes #77

Add development flavor support

---

lib/repositories/wallet_repository.dart

These values weren't read from the wallet blob correctly.

Compatibility bug fix: retrieve old wallet blob values correctly

---

lib/generated/rust/api/history.dart
lib/generated/rust/api/structs.dart
lib/generated/rust/frb_generated.dart
lib/states/wallet_state.dart
rust/src/api/history.rs
rust/src/api/structs.rs
rust/src/frb_generated.rs
rust/src/state/constants.rs

Add fees to outgoing tx struct

---

lib/screens/home/wallet/spend/amount_selection.dart

Return an error if the user tries to send more funds than what is currently available.
Closes #143

Check balance on amount screen

---

lib/screens/onboarding/get_started.dart

- Replace generic image with Rocket
- Remove flavor text with redirection to silentpayments.xyz

Revise final onboarding screen

---

lib/constants.dart
lib/global_functions.dart
lib/screens/home/wallet/receive/show_address.dart
lib/screens/home/wallet/wallet.dart
lib/screens/onboarding/tutorial/tutorial_1.dart
lib/screens/onboarding/tutorial/tutorial_2.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

This PR merges just the 'show address' screen from the `oslo-freedom-forum` branch.
Closes #144

Add reworked receive screen

---

lib/repositories/wallet_repository.dart

Remove support for old wallet format, if users have a very old wallet and haven't upgraded, this might be a problem, but it should be fine by now.

Remove support for deprecated wallet blob

---

lib/data/enums/warning_type.dart
lib/global_functions.dart
lib/screens/home/home.dart
lib/screens/home/wallet/receive/show_address.dart
lib/screens/home/wallet/spend/ready_to_send.dart
lib/screens/home/wallet/spend/transaction_sent.dart
lib/screens/home/wallet/wallet.dart
lib/screens/onboarding/recovery/seed_phrase.dart
lib/widgets/alerts/warning_message.dart
lib/widgets/buttons/footer/footer_button.dart

Add warning screens for:
- when using mainnet
- during recovery, to notify about bandwidth usage

Add warning screens

---

lib/constants.dart
lib/generated/rust/api/structs.dart
lib/generated/rust/frb_generated.dart
lib/main.dart
lib/main_dev.dart
lib/repositories/settings_repository.dart
lib/screens/home/home.dart
lib/screens/home/wallet/spend/fee_selection.dart
lib/screens/home/wallet/wallet.dart
lib/screens/settings/change_fiat.dart
lib/screens/settings/settings.dart
lib/services/fiat_exchange_rate_service.dart
lib/states/fiat_exchange_rate_state.dart
rust/src/api/structs.rs
rust/src/frb_generated.rs

Add option to choose fiat currency

---

lib/screens/home/home.dart

We currently don't have contacts support yet, so hide this screen.

Hide contacts screen from home
